### ISSUE TITLE
BSONDecoder help?

### ISSUE THREAD

**Issue by adhigadu** [Frizlab/BSONSerialization#1]
Hi 

I have a input-stream of bson documents coming from the server. 
I was trying to use the bsonObject function from BSONSerialization. But i believe the bson decoder is only able to decode the one document and is failing for all subsequent ones. 
My question is it possible to read and serialize multiple documents coming down in a inputstream? Any help will be much appreciated. 
Please find my code below. 

```swift
Alamofire.request(request as URLRequestConvertible).stream { (response) -> Void in
            print(response)
            do {
                let inputStream = InputStream(data: response)
                inputStream.open()
                let data = try BSONSerialization.bsonObject(with: inputStream)
                print(data)
            }catch{
                print(error)
            }
        }
```

**Comment by Frizlab** [comment]
Hello. In theory BSONSerialization should be able to decode multiple documents in the stream, but you’ll have to call `bsonObject(with:)` for each document to decode, each time passing the same stream.
Note I did not test this yet, so it might not work, but it should.

**Comment by adhigadu** [comment]
thanks @Frizlab , I will test this and see..

**Comment by adhigadu** [comment]
hi @Frizlab  i have tried passing the same stream and its not working. after passing for the first time it skipped the rest of the stream and failed to parse ..

**Comment by Frizlab** [comment]
I have reproduced the issue. Will release a fix ASAP.

**Comment by adhigadu** [comment]
thanks @Frizlab  appreciate it..

**Comment by Frizlab** [comment]
The bug should be fixed in 2.1.3.
Don’t hesitate to re-open the issue if it is not 🙃

**Comment by adhigadu** [comment]
thanks @Frizlab  will test and let you know..

**Comment by adhigadu** [comment]
@Frizlab  I have tried this logic and tried 

```swift  
func searaliseBsonStream() {
      let request = self.getRequest()
        Alamofire.request(request as URLRequestConvertible).stream { (response) -> Void in
            print(response)
            let inputStream = InputStream(data: response)
        do {
            inputStream.open()
            while inputStream.hasBytesAvailable { 
                let data = try BSONSerialization.bsonObject(with: inputStream)
                print(data)
               }
            }
        }
     }
```
It works for some time and then throwing the following error
noMoreData
16384 bytes
invalidElementType(114)
16384 bytes
invalidElementType(54)
8768 bytes
invalidElementType(116)
3992 bytes
invalidElementType(115)

However if i put a debugger inside the bsonObject function and run the code, its reading more documents and throwing less errors. 

I wonder if there is a thread issue or something.. Appreicate your help.. We been stuck on this for a while now and not sure what to do?
