### ISSUE TITLE
Inputstream failing 

### ISSUE THREAD

**Issue by adhigadu** [Frizlab/BSONSerialization#2]
@Frizlab I have tried this logic and tried
```swift
func searaliseBsonStream() {
    let request = self.getRequest()
    Alamofire.request(request as URLRequestConvertible).stream { (response) -> Void in
        print(response)
        let inputStream = InputStream(data: response)
        do {
            inputStream.open()
            while inputStream.hasBytesAvailable { 
                let data = try BSONSerialization.bsonObject(with: inputStream)
                print(data)
            }
        }
    }
}
```
It works for some time and then throwing the following error
noMoreData
16384 bytes
invalidElementType(114)
16384 bytes
invalidElementType(54)
8768 bytes
invalidElementType(116)
3992 bytes
invalidElementType(115)

However if i put a debugger inside the bsonObject function and run the code, its reading more documents and throwing less errors.

I wonder if there is a thread issue or something.. Appreicate your help.. We been stuck on this for a while now and not sure what to do?

Hi Sorry I had to create a new issue as i couldnt find a way to re open the current issue..

**Comment by Frizlab** [comment]
I’m lacking a bit of context to help you there.
Would you mind trying to create a reproducible test case showing this error? Or just send me the data that fails.

**Comment by adhigadu** [comment]
hi @Frizlab  I created a buffered stream instead of passing the inputstream directly and then breaking the stream document by document..  its working finally now.. thanks again for the help.. i will close this issue now..
