### ISSUE TITLE
Further development ?

### ISSUE THREAD

**Issue by vexy** [Frizlab/BSONSerialization#6]
Hello @Frizlab,

As per your comments:
```
"...I’ll work seriously on the project if it gains enough attention. Feel free to open issues, I’ll do my best to answer."""
```

I'm willing to help where needed. Having said that, would it be beneficial for project to turn "TODO" section into standalone Project ?

That way, we can work together on improving this neat library 😀 

Cheers !

**Comment by Frizlab** [comment]
I’m not sure what you mean by turning the TODO section into standalone projects? You’re welcome to contribute via PRs in separate branches (or even the same, if you’re doing a PR it doesn't matter).

**Comment by vexy** [comment]
@Frizlab, thanks for clarifying the way to contribute. I'll try to contribute, time permitting.

Anyhow, I was thinking of opening up GitHub projects and turning _TODO_ section from `README` into standalone tasks.
Perhaps that way the clarity for future works would be even greater.
